ALTER TABLE products.products ADD COLUMN IF NOT EXISTS weight_grams INT NOT NULL DEFAULT 500;
ALTER TABLE products.products ADD COLUMN IF NOT EXISTS length_cm INT NOT NULL DEFAULT 10;
ALTER TABLE products.products ADD COLUMN IF NOT EXISTS width_cm INT NOT NULL DEFAULT 10;
ALTER TABLE products.products ADD COLUMN IF NOT EXISTS height_cm INT NOT NULL DEFAULT 10;
