ALTER TABLE products.products ADD COLUMN IF NOT EXISTS art_type VARCHAR(20) NOT NULL DEFAULT 'NONE';
ALTER TABLE products.products ADD COLUMN IF NOT EXISTS art_width_cm INT NOT NULL DEFAULT 0;
ALTER TABLE products.products ADD COLUMN IF NOT EXISTS art_height_cm INT NOT NULL DEFAULT 0;
